### ISSUE TITLE
DOC - Module Order

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#31]
The [Module Order](https://pvrpm.readthedocs.io/en/latest/tutorial_getting_started.html#module-order) documentation seems to infer that I should look up my module order in a gigantic table from [here](https://nrel-pysam.readthedocs.io/en/master/Configs.html#sam-simulation-configurations).

However, it's much simpler to do something like the following:

```python
>>> import json
>>> with open("my_sam_case.json", "r") as f:
...     data = json.load(f)
>>> modules = {x: data[x] for x in data.keys() if x.startswith("compute_module")}
>>> modules
{'compute_module_0': 'pvwattsv8', 'compute_module_1': 'belpe', 'compute_module_2': 'grid', 'compute_module_3': 'utilityrate5', 'compute_module_4': 'cashloan'}
```

**Comment by brandons209** [comment]
I'm not sure what you mean. Are you saying to have users create a JSON file for loading module order? Or including a json file that dictates all possible module orders and orders them properly?

**Comment by blthayer** [comment]
Maybe I'm confused :smile: 

My understanding is that after exporting the SAM case to `.json`, we need to reflect the module order found in the exported `json` into the `.yaml` configuration file under the `module_order` key, correct?

I suppose I don't understand why a user needs to look up the module order in the [gigantic table](https://nrel-pysam.readthedocs.io/en/master/Configs.html#sam-simulation-configurations).

Maybe it'd be a nice feature add for `pvrpm` to parse the `json` and extract the module order itself (*e.g.*, using something similar to the code above)?

Is it ever allowed to put a different module order in the `yaml` config file than what comes out of the exported `json` case file? If not, this manual transcription step should be eliminated in my opinion. Plenty of room for user error :smile:

**Comment by brandons209** [comment]
The layout of the JSON files isn't the module order. Each JSON file represents a specific module and the order of all of those modules must follow the order in the table as you mentioned. If you put a different module order then what is needed the SAM simulation won't work. I think its possible to add a feature to automatically do this.

Basically, you got a bunch of modules on export to JSON from SAM. Then you would see all the modules you have, find the matching order in the table, then order them properly in the `.yaml` config file.
