### ISSUE TITLE
DOC - SAM only exports 1 `.json` file

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#39]
The [docs](https://pvrpm.readthedocs.io/en/latest/tutorial_2getting_started.html#exporting-the-sam-case) say the following with respect to SAM's `json` export:

> Once this is done, the selected folder will contain a few JSON files. The names of these files will follow the convention of case-name_module.json where case-name is the name of the case, and module is the module that JSON represents.

However, when I export using the latest version of SAM (`2021.12.2`), only one `json` file is exported.

So, either:
- My SAM installation isn't working correctly, or
- The docs should be updated :smile:

**Comment by brandons209** [comment]
Pretty sure its your SAM installation not working correctly, this is unexpected behavior. I am looking into it.

**Comment by brandons209** [comment]
See #36 I will make sure the correct option for generating the JSON files stressed in the docs.

**Comment by blthayer** [comment]
Thanks. SAM did indeed export several JSON files instead of one once I used the `PySAM JSON` export instead of the `JSON for inputs` option that was originally documented.
