### ISSUE TITLE
Integer number of inverters per transformer

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#45]
On a whim, I changed my configured number of transformers (`num_transformers`) from `1` to `3`. When attempting to run the case, I get the following error: `Error loading and verifying case: There must be an integer number of inverters per transformer!`

This seems like a bit of a nuisance error IMO. It seems well within the realm of possibility (though maybe not typical) that a different number of inverters might be "under/downstream" of the different transformers. 

Perhaps `pvrpm` could round and emit a warning, or model transformers having different numbers of inverters beneath them.

**Comment by brandons209** [comment]
I think we could round, but from the way PVRPM is built and my understanding an even number of inverters to transformers is needed. Rounding and emitting a warning that it was rounded can work although I am of the belief that the user should have a proper configuration before running rather then having a possibly incorrect configuration and assuming by rounding.

**Comment by blthayer** [comment]
Fair enough!
