### ISSUE TITLE
(Optional): Threads convention

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#46]
Purely optional for JOSS review, just sharing my experience :smile: 

In my experience, tools that support multiprocessing or multi-threading typically use `-1` to designate "use all cores" while `0` and `1` mean unparallelized (serial). `pvrpm`'s convention has `0` indicate "use all cores"

**Comment by brandons209** [comment]
Fixed in a098c23e4f051e1a9f7099464984b2ec3331c258
