### ISSUE TITLE
Optional: Support configuration from PySAM (maybe?)

### ISSUE THREAD

**Issue by SarthakJariwala** [FSEC-Photovoltaics/pvrpm-lcoe#51]
Could you also use pvrpm directly with PySAM?

Instead of creating a case in SAM and exporting it, would it also be possible to develop the case in PySAM and export the configurations to use them with pvrpm? This would eliminate the need for users to download and interact with the GUI every time they want to model a new case.

**Comment by brandons209** [comment]
You can, following PySAM's documentation. However their documentation recommends to use the SAM interface as its tedious to configure every variable needed manually for a system configuration, compared to exporting the JSON files from SAM.

https://nrel-pysam.readthedocs.io/en/master/Examples.html

As for support in PVRPM, a user can write their own Python script to generate the JSONs needed for PVRPM to work, but it seems to be easier to use the GUI. I also think it opens up for a lot more user error compared to using the GUI. I think it would be possible to add in the functionality of PVRPM being able to take in prebuilt module objects but it would be non-trivial.

**Comment by SarthakJariwala** [comment]
Ok, thanks for the information. Having worked with PySAM before, I agree with you; it is pretty tedious to set up the simulation.
