### ISSUE TITLE
DOC: Document public API

### ISSUE THREAD

**Issue by SarthakJariwala** [FSEC-Photovoltaics/pvrpm-lcoe#52]
The API section in the docs is [empty](https://pvrpm.readthedocs.io/en/latest/api/modules.html). If the API listed there isn't supposed to be public API, I would recommend not listing it there. 

As I understand, pvrpm is intended to be used from the command line (and not imported as a module), and as such, commands `run`, `verify` `sim` are the public API. I would suggest documenting those commands in more detail (see #50).

**Comment by brandons209** [comment]
Huh, odd, was showing up fine locally. I'll fix it. Also, PVRPM can be used from both the command line and imported as modules. to manually setup and run a case with your own wrapper scripts.

**Comment by brandons209** [comment]
Fixed in 4899e72e970b94dcf715e760ba2e0a2aebf553a2
