### ISSUE TITLE
[FEATURE] y-axis label for LCOE Box Plot

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#58]
Looking through the results, all plots except the "LCOE Box Plot" have appropriate y-axis labels.
![LCOE Box Plot](https://user-images.githubusercontent.com/14652512/156938329-1cc2f548-f496-4648-9a3d-ea1b989c94d9.png)

**Comment by brandons209** [comment]
Will do, also I am a bit worried if your LCOE is in the thousands. Definitely should not be that high.

**Comment by brandons209** [comment]
fixed in 75e52c7

**Comment by blthayer** [comment]
@brandons209

> Will do, also I am a bit worried if your LCOE is in the thousands. Definitely should not be that high.

If I were to guess, it's related to the small system size that I used, combined with the default failure/monitoring configurations which are likely expensive for the small amount of energy output. Just speculating, though.

**Comment by brandons209** [comment]
Yeah probably, just that even in systems I've seen its usually not that high, unless you had some super high amount of failures and availability was very low.
