### ISSUE TITLE
[FEATURE] (OPTIONAL) Default Branch Name

### ISSUE THREAD

**Issue by blthayer** [FSEC-Photovoltaics/pvrpm-lcoe#59]
100% optional for JOSS review.

Consider changing the name of your primary branch from `master` to something else like `main`. Here are the [GitHub docs](https://github.com/github/renaming) related to branch renaming.

I'd be happy to discuss rationale for this suggestion if desired.

**Comment by brandons209** [comment]
Hmm, I'll take a look at doing this. My first thought thought is that it isn't really necessary, though.

**Comment by brandons209** [comment]
I would like to hear your rationale though.

**Comment by blthayer** [comment]
Necessary? Absolutely not. A nice thing to do? Arguably, yes.

I'm not going to claim to possess an ability to speak eloquently on this topic, but the short version is that getting away from terminology associated with slavery makes for a more inclusive environment, and fields such as engineering, programming, software development, etc. have historically not been particularly inclusive or diverse.

I'll be the first one to say that, in my personal opinion, some folks take notions of "political correctness" over the top, but I think the default branch name change from `master` to `main` is easy and sends the right message.

Here are some _very_ quick (< 2 minute) reads on the topic:
- https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main
- https://sfconservancy.org/news/2020/jun/23/gitbranchname/
- Here's a fun couple of tweets where a guy by the name of Tobie initially [dismissed the notion that "master" is racist](https://twitter.com/tobie/status/1269929597203873793) and then subsequently [changed his mind](https://twitter.com/tobie/status/1270290278029631489) after finding evidence that the name stemmed from master/slave, _not_ from "master copy."

The first line from the Software Freedom Conservancy's post (second link) is worth quoting:

> Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.

At the end of the day, this is completely up to you as the owner of the repository. As I mentioned, your JOSS review is not at all contingent on making this change.

**Comment by brandons209** [comment]
Huh. I've never really looked into it. I'll go ahead and look into the links you've posted and decide on what to do. Thanks for the information!

I'll go ahead and close the issue as well.
